---

- name: repositories key
  apt_key: >
    url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://packages.elasticsearch.org/elasticsearch/1.2/debian stable main
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=present
  with_items:
    - elasticsearch
  sudo: yes

- name: service
  service: >
    name=elasticsearch
    state=started
    enabled=yes
  sudo: yes
